function cargarTextos() {
    var textos = [
        "por Andrés Bestard Maggio. <br><br> Presiona < o > para pasar de página",
        "",
        '"Aqui estoy siguiendo las huellas de Aquellos que se fueron...<br>' + 'Estoy caminando por la senda que dejaron Aquellos que se fueron...<br>' + 'Sigo el rastro de sus pisadas...<br>' + 'Aquellos que se fueron me han hablado desde lejos...<br>' + 'Ellos desde el infinito me han hablado...<br>' + 'Las huellas de aquellos que se fueron Están aquí."<br>' + '-Canto shamánico selknam (ona)<br>',
        '"Andar andando"',
        '"Cuántas leguas hay al cielo"',
        '"Al tranco"',
        '"Sacrificio"' + '&emsp;"El angelito"',
        '"Con dos lunas"',
        '"Movilizados"',
        '"Al trote"',
        '"Con ritmo"',
        '"Continuo"',
        '"Sin parar"',
        '"Con el sol al hombro"',
        '"No nos dejes"',
        '"Con los chicos"',
        '"Danzando"',
        '"Es imposible callar"',
        '"Contra las agujas del reloj"',
        '"Sin salida"',
        '"Ronda mística"',
        '"Corrida espiralada" (otra búsqueda)',
        '"Caminantes"',
        '"Caminando"',
        '"Al infinito"',
        '"La vuelta"',
        '"Un alto en el camino"',
        '"Cae la tarde"',
        '"Tiempos tiernos"',
        '"Hay qué seguir"',
        '"¿A dónde?"',
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        '"A la ciudad"',
        '"Ciudadanos"',
        '"De paso"',
        '"Los bombistos" (son capiangos)',
        '"Esperando el colectivo" (tanto caminar)',
        '"Autómatas"' + '&emsp;"Sin destino"',
        '"Al trabajo" (sobrehumanos)',
        '"Cartoneros"',
        '"Cirujas"',
        '"Los ángeles de la calle"',
        '"La noche" (vino al fin tapando la pobreza)',
        '"Esperando el día"',
        "",
        '"Subsuelo" (¿Dónde caímos?)',
        '"Buscando la salida"',
        '"Santiamén"',
        '"Buscando la salida" (en bicicleta)',
        '"Yo no digo misa ni rezo"',
        '"Cada vez más abajo"',
        '"La salida"',
        '"¿La encontraron?"',
        '"Día"',
        '"Noche"',
        '"Noche y Día"',
        '"Con jaguares"',
        '"Escapando?"',
        '"Trepando"',
        '"Desde abajo"',
        '"Miedo Ancestral"',
        '"Miedo a la soledad"',
        '"Miedo a la nada"',
        '"¿La salida dónde está?"',
        '"Se hizo la luz"',
        '"¿La realidad por dónde pasa?"',
        "",
        '"Con la muerte al hombro"',
        "",
        '"¿A quién enterramos?"',
        "",
        "",
        '"Cuanto más caminamos" (más nos pesa)',
        '"Llegamos"',
        '"Invasión" (encuentro de dos culturas)' + 'Lo vivo está muerto, lo muerto está vivo',
        '"Búsqueda americana"' + "Caminando por el sendero de la historia desde los hijos del sol a los hijos de la calle",
        '"La última noche" (vida)',
        '"La conquista de Córdoba" (Muerte)',
        '"Domesticando a los gringos"',
        '"Defendiendo lo nuestro"',
        '"Una tregua"',
        '"Malón" (Ley del Talión)',
        '"Cimarrones y milicos" (metamorfosis gaucha)',
        '"Perdimos lo nuestro"',
        '"Y en el 2000 también" (La historia vuelve a repetirse)',
        '"El pueblo unido"',
        '"Teoría + Teoría = Confusión"' + '&emsp;"¿Quiénes somos?"',
        '"Imigrantes" (Así fueron cayendo)',
        '"Cuidado con los líderes"',
        '"No videntes"',
        '"Igual los seguimos"',
        '"La América"',
        '"Dos puntos de vista" (una raíz que brota y los mediocres las cortan)',
        '"Atrás el desierto" (Llegó la cultura)',
        '"Éxodo (por sobrevivir)"' + 'o ¿Por los votos?',
        '"La gran ciudad"+"¿Quién cuida el interior?"',
        '"Los trepadores" (pelea personal) El uno contra todo',
        '"Una salida" (los brotes)',
        '"Unir las fuerzas"',
        '"Somos cómo un árbol plantado en América"',
        '"Con raices muy profundas"',
        "",
        '"El blanco tiene solo sus ramas sobre América" "Apartadas de su propia esencia"',
        '"La tarea es encontrar el tronco que nos une" Melesio Zamora Wichi',
        '"Por un objetivo en común"',
        '"Nuevo Proyecto" (Una nueva planta)',
        '"Triunfa la vida"',
        "",
        '"Es parir"',
        "",
        '"Dos"',
        "",
        '"Tres"',
        '"Somos"',
        '"La familia"',
        '"En marcha"',
        '"Por siempre"',
        'FIN',
    ];
    return textos;
}